name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  discord_notify:
      runs-on: ubuntu-latest
      name: Discord Webhook Notify
      steps:
        - name: Discord test success notify
          uses: rjstone/discord-webhook-notify@v1
          with:
              severity: info
              details: Test succeeded.
              webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

            
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
